definitions:
  models.Student:
    properties:
      age:
        type: integer
      grade:
        description: 年级
        type: integer
      id:
        type: integer
      major:
        description: 专业
        type: string
      name:
        type: string
    required:
      - id
    type: object
  models.Teacher:
    properties:
      gender:
        description: 性别，false 表示男，true 表示女
        type: boolean
      grade:
        description: 年级
        type: integer
      id:
        type: integer
      major:
        description: 专业
        type: string
      name:
        type: string
    required:
      - id
    type: object
  result.Result:
    properties:
      code:
        description: |-
          状态码
          2xx 表示请求成功，3xx 表示重定向，4xx 表示客户端错误，5xx 表示服务端错误
        type: integer
      data:
        description: 数据
        type: object
      msg:
        description: 状态码描述信息
        type: string
    type: object
info:
  contact: { }
  description: 基于 go 实现的后端，用于处理与保存人脸识别相关信息
  title: 项目管理-人脸识别签到系统
  version: 0.0.1
paths:
  /course/list:
    get:
      description: 基于老师id、教室id 查询课程
      parameters:
        - description: 老师id，非必要
          in: query
          name: teacherId
          type: integer
        - description: 教室id，非必要
          in: query
          name: classRoomId
          type: integer
        - description: 页号
          in: query
          name: pageNumber
          type: integer
        - description: 页大小
          in: query
          name: pageSize
          type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/result.Result'
              - properties:
                  data:
                    additionalProperties: true
                    type: object
                type: object
      summary: 查询课程
      tags:
        - 课程
  /course/student/list:
    get:
      description: 基于学生id 查询课程
      parameters:
        - description: 学生id
          in: query
          name: studentId
          type: integer
        - description: 页号
          in: query
          name: pageNumber
          type: integer
        - description: 页大小
          in: query
          name: pageSize
          type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/result.Result'
              - properties:
                  data:
                    additionalProperties: true
                    type: object
                type: object
      summary: 查询课程
      tags:
        - 课程
  /record:
    post:
      description: 基于学生id、教室id 插入记录
      parameters:
        - description: 学生id
          in: query
          name: studentId
          type: integer
        - description: 教室id
          in: query
          name: classRoomId
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 创建记录
      tags:
        - 记录
  /record/list:
    get:
      description: 基于学生id、课程id 查询记录
      parameters:
        - description: 课程id，非必须
          in: query
          name: courseId
          type: integer
        - description: 日期，格式为YYYY-MM-DD，非必须
          in: query
          name: date
          type: string
        - description: 页号，从一开始
          in: query
          name: pageNumber
          required: true
          type: integer
        - description: 页大小
          in: query
          name: pageSize
          required: true
          type: integer
        - description: 学生id，非必须
          in: query
          name: studentId
          type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/result.Result'
              - properties:
                  data:
                    additionalProperties: true
                    type: object
                type: object
      summary: 查询记录
      tags:
        - 记录
  /student:
    put:
      description: 基于学生 ID 更新学生信息，需要更新哪些填写哪些信息，ID 是必要的
      parameters:
        - description: 学生
          in: body
          name: student
          schema:
            $ref: '#/definitions/models.Student'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 更新学生信息
      tags:
        - 学生
  /student/{id}:
    get:
      description: 基于学生 id 获取学生信息
      parameters:
        - description: 学生id
          in: path
          name: id
          type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/result.Result'
              - properties:
                  data:
                    $ref: '#/definitions/models.Student'
                type: object
      summary: 获取学生
      tags:
        - 学生
  /student/list:
    get:
      description: 分页获取学生列表
      parameters:
        - description: 页号
          in: query
          name: pageNumber
          type: integer
        - description: 页大小
          in: query
          name: pageSize
          type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/result.Result'
              - properties:
                  data:
                    additionalProperties: true
                    type: object
                type: object
      summary: 获取学生列表
      tags:
        - 学生
  /teacher:
    put:
      description: 基于老师 ID 更新老师信息，需要更新哪些填写哪些信息，ID 是必要的
      parameters:
        - description: 老师
          in: body
          name: pageNumber
          schema:
            $ref: '#/definitions/models.Teacher'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 更新老师信息
      tags:
        - 老师
  /teacher/{id}:
    get:
      description: 基于老师 id 获取老师信息
      parameters:
        - description: 老师id
          in: path
          name: id
          type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/result.Result'
              - properties:
                  data:
                    $ref: '#/definitions/models.Teacher'
                type: object
      summary: 获取老师
      tags:
        - 老师
  /teacher/list:
    get:
      description: 分页获取老师列表
      parameters:
        - description: 页号
          in: query
          name: pageNumber
          type: integer
        - description: 页大小
          in: query
          name: pageSize
          type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/result.Result'
              - properties:
                  data:
                    additionalProperties: true
                    type: object
                type: object
      summary: 获取老师列表
      tags:
        - 老师
swagger: "2.0"
